<?php
/*
 * VizuHAL - Générez des stats HAL - Generate HAL stats
 *
 * Copyright (C) 2023 Olivier Troccaz (olivier.troccaz@cnrs.fr) and Laurent Jonchère (laurent.jonchere@univ-rennes.fr)
 * Released under the terms and conditions of the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.txt)
 *
 * Préfixe DOI d'éditeurs - Publisher DOI prefix
 */
 
$Prefixe_DOI = array(
0 => array("editeur_ng"=>"ACM", "editeur"=>"Association for Computing Machinery", "prefixe"=>"10.1145"),
1 => array("editeur_ng"=>"ACS", "editeur"=>"American Chemical Society", "prefixe"=>"10.1021"),
2 => array("editeur_ng"=>"ACS", "editeur"=>"American Chemical Society", "prefixe"=>"10.26434"),
3 => array("editeur_ng"=>"ACS", "editeur"=>"American Chemical Society (ACS)", "prefixe"=>"10.29200"),
4 => array("editeur_ng"=>"American Society of Hematology", "editeur"=>"American Society of Hematology", "prefixe"=>"10.1182"),
5 => array("editeur_ng"=>"APS", "editeur"=>"American Physical Society", "prefixe"=>"10.1103"),
6 => array("editeur_ng"=>"APS", "editeur"=>"American Physical Society (APS)", "prefixe"=>"10.29172"),
7 => array("editeur_ng"=>"Biomed Central", "editeur"=>"Springer (Biomed Central Ltd.)", "prefixe"=>"10.1186"),
8 => array("editeur_ng"=>"BMJ", "editeur"=>"BMJ", "prefixe"=>"10.1136"),
9 => array("editeur_ng"=>"Cairn", "editeur"=>"CAIRN", "prefixe"=>"10.3917"),
10 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press", "prefixe"=>"10.1017"),
11 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Australian Academic Press)", "prefixe"=>"10.1375"),
12 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Materials Research Society)", "prefixe"=>"10.1557"),
13 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press pre-prints", "prefixe"=>"10.33774"),
14 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Society for the Promotion of Roman Studies)", "prefixe"=>"10.3815"),
15 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Entomological Society of Canada)", "prefixe"=>"10.4039"),
16 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Mathematical Association of America)", "prefixe"=>"10.5948"),
17 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (CUP)", "prefixe"=>"10.5949"),
18 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Anthem Press)", "prefixe"=>"10.7135"),
19 => array("editeur_ng"=>"Cambridge UP", "editeur"=>"Cambridge University Press (Nottingham University Press)", "prefixe"=>"10.7313"),
20 => array("editeur_ng"=>"Dalloz", "editeur"=>"", "prefixe"=>""),
21 => array("editeur_ng"=>"EDP Sciences", "editeur"=>"EDP Sciences", "prefixe"=>"10.1051"),
22 => array("editeur_ng"=>"EDP Sciences", "editeur"=>"EDP Sciences", "prefixe"=>"10.2515"),
23 => array("editeur_ng"=>"EDP Sciences", "editeur"=>"EDP Sciences", "prefixe"=>"10.2516"),
24 => array("editeur_ng"=>"EDP Sciences", "editeur"=>"EDP Sciences", "prefixe"=>"10.9742"),
25 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Academic Press", "prefixe"=>"10.1006"),
26 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier", "prefixe"=>"10.1016"),
27 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - WB Saunders", "prefixe"=>"10.1053"),
28 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier- Churchill Livingstone", "prefixe"=>"10.1054"),
29 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Mosby", "prefixe"=>"10.1067"),
30 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Urban & Fischer Verlag", "prefixe"=>"10.1078"),
31 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Ediciones Doyma", "prefixe"=>"10.1157"),
32 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier- Hanley and Belfus Inc.", "prefixe"=>"10.1197"),
33 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Institution of Chemical Engineers", "prefixe"=>"10.1205"),
34 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier- Spektrum Akademischer Verlag", "prefixe"=>"10.1240"),
35 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Ambulatory Pediatric Associates", "prefixe"=>"10.1367"),
36 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Medicine Publishing Company", "prefixe"=>"10.1383"),
37 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Biophysical Society", "prefixe"=>"10.1529"),
38 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Wilderness Medical Society", "prefixe"=>"10.1580"),
39 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - American Society for Experimental Neurotherapeutics", "prefixe"=>"10.1602"),
40 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier (Society for Range Management)", "prefixe"=>"10.2111"),
41 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - American Society for Investigative Pathology", "prefixe"=>"10.2353"),
42 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - International Federation of Automatic Control (IFAC)", "prefixe"=>"10.3182"),
43 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - CIG Media Group LP", "prefixe"=>"10.3816"),
44 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Colegio Nacional de Opticos-Optometristas de Espana", "prefixe"=>"10.3921"),
45 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Mayo Clinic Proceedings", "prefixe"=>"10.4065"),
46 => array("editeur_ng"=>"Elsevier", "editeur"=>"Elsevier - Central Mining Institute", "prefixe"=>"10.7424"),
47 => array("editeur_ng"=>"Frontiers", "editeur"=>"Frontiers Media SA", "prefixe"=>"10.3389"),
48 => array("editeur_ng"=>"Frontiers", "editeur"=>"Frontiers Media SA", "prefixe"=>"10.4175"),
49 => array("editeur_ng"=>"IEEE", "editeur"=>"Institute of Electrical and Electronics Engineers", "prefixe"=>"10.1109"),
50 => array("editeur_ng"=>"IEEE", "editeur"=>"Institute of Electrical and Electronics Engineers - Bell Labs", "prefixe"=>"10.15325"),
51 => array("editeur_ng"=>"IEEE", "editeur"=>"Institute of Electrical and Electronics Engineers", "prefixe"=>"10.23919"),
52 => array("editeur_ng"=>"IOP", "editeur"=>"IOP Publishing", "prefixe"=>"10.1088"),
53 => array("editeur_ng"=>"IOP", "editeur"=>"IOP Publishing - Europhysics Letters", "prefixe"=>"10.1209"),
54 => array("editeur_ng"=>"Lexis", "editeur"=>"Lexis Publisher (OMICS)", "prefixe"=>""),
55 => array("editeur_ng"=>"Lextenso", "editeur"=>"", "prefixe"=>""),
56 => array("editeur_ng"=>"MDPI", "editeur"=>"MDPI AG", "prefixe"=>"10.20944"),
57 => array("editeur_ng"=>"MDPI", "editeur"=>"MDPI AG - Encyclopedia", "prefixe"=>"10.32545"),
58 => array("editeur_ng"=>"MDPI", "editeur"=>"MDPI AG", "prefixe"=>"10.3390"),
59 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"Springer Nature", "prefixe"=>"10.1013"),
60 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"Springer Nature", "prefixe"=>"10.1038"),
61 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"Springer Nature", "prefixe"=>"10.1057"),
62 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"SpringerNature", "prefixe"=>"10.26777"),
63 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"SpringerNature", "prefixe"=>"10.26778"),
64 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"Springer Nature - VVW", "prefixe"=>"10.33283"),
65 => array("editeur_ng"=>"Nature Publishing Group", "editeur"=>"Springer Nature", "prefixe"=>"10.3858"),
66 => array("editeur_ng"=>"OpenEdition", "editeur"=>"OpenEdition", "prefixe"=>"10.4000"),
67 => array("editeur_ng"=>"OSA", "editeur"=>"The Optical Society", "prefixe"=>"10.1364"),
68 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - Lippincott Williams & Wilkins", "prefixe"=>"10.1097"),
69 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies Wolters Kluwer -American Heart Association", "prefixe"=>"10.1161"),
70 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - International Pediatric Research Foundation", "prefixe"=>"10.1203"),
71 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - American Academy of Neurology", "prefixe"=>"10.1212"),
72 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - Anesthesia & Analgesia", "prefixe"=>"10.1213"),
73 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - Neurosurgery", "prefixe"=>"10.1227"),
74 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters-Kluwer) - American College of Sports Medicine", "prefixe"=>"10.1249"),
75 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - Triological Society", "prefixe"=>"10.1288"),
76 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - National Strength & Conditioning", "prefixe"=>"10.1519"),
77 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - Italian Federation of Cardiology", "prefixe"=>"10.2459"),
78 => array("editeur_ng"=>"Ovid", "editeur"=>"Ovid Technologies (Wolters Kluwer) - ENSTINET", "prefixe"=>"10.7123"),
79 => array("editeur_ng"=>"Oxford UP", "editeur"=>"Oxford University Press", "prefixe"=>"10.1093"),
80 => array("editeur_ng"=>"PLOS", "editeur"=>"Public Library of Science", "prefixe"=>"10.1371"),
81 => array("editeur_ng"=>"PLOS", "editeur"=>"Public Library of Science (PLoS)", "prefixe"=>"10.24196"),
82 => array("editeur_ng"=>"RSC", "editeur"=>"The Royal Society of Chemistry", "prefixe"=>"10.1039"),
83 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications - Technomic Publishing Company", "prefixe"=>"10.1106"),
84 => array("editeur_ng"=>"Sage", "editeur"=>"SAGE Publications", "prefixe"=>"10.1177"),
85 => array("editeur_ng"=>"Sage", "editeur"=>"SAGE", "prefixe"=>"10.14240"),
86 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications- Academy of Traumatology", "prefixe"=>"10.1528"),
87 => array("editeur_ng"=>"Sage", "editeur"=>"SagePublications - National Association of School Nurses", "prefixe"=>"10.1622"),
88 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications-International Institute for Environment and Development", "prefixe"=>"10.1630"),
89 => array("editeur_ng"=>"Sage", "editeur"=>"Sage - Corwin", "prefixe"=>"10.17322"),
90 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications - Bulletin of the Atomic Scientists", "prefixe"=>"10.2968"),
91 => array("editeur_ng"=>"Sage", "editeur"=>"SAGE Publications", "prefixe"=>"10.31124"),
92 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications (JRAAS Limited)", "prefixe"=>"10.3317"),
93 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications - Reference E-Books", "prefixe"=>"10.4135"),
94 => array("editeur_ng"=>"Sage", "editeur"=>"Sage Publications (Prufrock Press, Inc.)", "prefixe"=>"10.4219"),
95 => array("editeur_ng"=>"SIAM", "editeur"=>"Society for Industrial and Applied Mathematics", "prefixe"=>"10.1137"),
96 => array("editeur_ng"=>"SPIE", "editeur"=>"SPIE - International Society for Optical Engineering", "prefixe"=>"10.1117"),
97 => array("editeur_ng"=>"Springer", "editeur"=>"Springer-Verlag", "prefixe"=>"10.1007"),
98 => array("editeur_ng"=>"Springer", "editeur"=>"Springer (Kluwer Academic Publishers)", "prefixe"=>"10.1023"),
99 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Ecomed Publishers", "prefixe"=>"10.1065"),
100 => array("editeur_ng"=>"Springer", "editeur"=>"Springer (Kluwer Academic Publishers - Biomedical Engineering Society (BMES))", "prefixe"=>"10.1114"),
101 => array("editeur_ng"=>"Springer", "editeur"=>"Springer-Verlag", "prefixe"=>"10.1140"),
102 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Society of Surgical Oncology", "prefixe"=>"10.1245"),
103 => array("editeur_ng"=>"Springer", "editeur"=>"Springer (Biological Procedures Online)", "prefixe"=>"10.1251"),
104 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - ASM International", "prefixe"=>"10.1361"),
105 => array("editeur_ng"=>"Springer", "editeur"=>"Springer Fachmedien Wiesbaden GmbH", "prefixe"=>"10.1365"),
106 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Cell Stress Society International", "prefixe"=>"10.1379"),
107 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - FD Communications", "prefixe"=>"10.1381"),
108 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Humana Press", "prefixe"=>"10.1385"),
109 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - RILEM Publishing", "prefixe"=>"10.1617"),
110 => array("editeur_ng"=>"Springer", "editeur"=>"Springer Publishing Company", "prefixe"=>"10.1891"),
111 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Adis", "prefixe"=>"10.2165"),
112 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Psychonomic Society", "prefixe"=>"10.3758"),
113 => array("editeur_ng"=>"Springer", "editeur"=>"Springer (Cases Network, Ltd.)", "prefixe"=>"10.4076"),
114 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - The Korean Society of Pharmaceutical Sciences and Technology", "prefixe"=>"10.4333"),
115 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Real Academia de Ciencias Exactas, Fisicas y Naturales", "prefixe"=>"10.5052"),
116 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - (backfiles)", "prefixe"=>"10.5819"),
117 => array("editeur_ng"=>"Springer", "editeur"=>"Springer - Global Science Journals", "prefixe"=>"10.7603"),
118 => array("editeur_ng"=>"Taylor & Francis", "editeur"=>"Informa UK (Taylor & Francis)", "prefixe"=>"10.1080"),
119 => array("editeur_ng"=>"Taylor & Francis", "editeur"=>"Informa UK (Taylor & Francis Books)", "prefixe"=>"10.1531"),
120 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (John Wiley & Sons)", "prefixe"=>"10.1002"),
121 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Munksgaard)", "prefixe"=>"10.1034"),
122 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Blackwell Publishing)", "prefixe"=>"10.1046"),
123 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Blackwell Publishing)", "prefixe"=>"10.1111"),
124 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (The Physiological Society)", "prefixe"=>"10.1113"),
125 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (New York Academy of Sciences)", "prefixe"=>"10.1196"),
126 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Royal Meteorological Society)", "prefixe"=>"10.1256"),
127 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (International Life Sciences Institute)", "prefixe"=>"10.1301"),
128 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (British Psychological Society)", "prefixe"=>"10.1348"),
129 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley(American Society Bone & Mineral Research)", "prefixe"=>"10.1359"),
130 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Physiological Reports)", "prefixe"=>"10.14814"),
131 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Canadian Academic Accounting Association)", "prefixe"=>"10.1506"),
132 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (International Journal of Psychoanalysis)", "prefixe"=>"10.1516"),
133 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Rural Sociological Society)", "prefixe"=>"10.1526"),
134 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley Blackwell (Royal College of Obstetricians & Gynecologist)", "prefixe"=>"10.1576"),
135 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Robotic Publications)", "prefixe"=>"10.1581"),
136 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (American College of Veterinary Internal Medicine)", "prefixe"=>"10.1892"),
137 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley", "prefixe"=>"10.18934"),
138 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Society of Environmental Toxicology and Chemistry)", "prefixe"=>"10.1897"),
139 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Equine Veterinary Journal)", "prefixe"=>"10.2746"),
140 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley Blackwell (Blackwell Publishing - Foundation for Cellular and Molecular Medicine)", "prefixe"=>"10.2755"),
141 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (AHRC Research Centre)", "prefixe"=>"10.2966"),
142 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Comparative Legislative Research Center)", "prefixe"=>"10.3162"),
143 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Opulus Press)", "prefixe"=>"10.3170"),
144 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (American Cancer Society)", "prefixe"=>"10.3322"),
145 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Production and Operations Management)", "prefixe"=>"10.3401"),
146 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (New York Academy of Sciences E-Briefings)", "prefixe"=>"10.3405"),
147 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (The Wildlife Society)", "prefixe"=>"10.4004"),
148 => array("editeur_ng"=>"Wiley", "editeur"=>"Wiley (Teachers of English to Speakers of Other Languages, Inc.)", "prefixe"=>"10.5054"),
149 => array("editeur_ng"=>"AIP", "editeur"=>"American Institute of Paris)", "prefixe"=>"10.1063")
);
?>